BASE: ['']
TOOLBOX_MODE: "only_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 30
  LR: 9e-3
  MODEL_FILE_NAME: COHFACE_COHFACE_COHFACE_efficientphys
  DATA:
    FS: 20
    DATASET: COHFACE
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/scratch/manne.sa/data/ACL_23/COHFACE/cohface/"          # Raw dataset path, need to be updated
    #CACHED_PATH: "/scratch/manne.sa/data/ACL_23/COHFACE/proc"    # Processed dataset save path, need to be updated
    CACHED_PATH: "/scratch/manne.sa/data/ACL_23/COHFACE/class_proc/"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.5
    PREPROCESS :
      DATA_TYPE: ['Standardized']
      #LABEL_TYPE: DiffNormalized
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 72
      W: 72
VALID:
  DATA:
    FS: 20
    DATASET: COHFACE
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/scratch/manne.sa/data/ACL_23/COHFACE/cohface/"          # Raw dataset path, need to be updated
    #CACHED_PATH: "/scratch/manne.sa/data/ACL_23/COHFACE/proc"    # Processed dataset save path, need to be updated
    CACHED_PATH: "/scratch/manne.sa/data/ACL_23/COHFACE/class_proc/"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.5
    END: 0.7
    PREPROCESS:
      DATA_TYPE: ['Standardized']
      #LABEL_TYPE: DiffNormalized
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 72
      W: 72
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson']
  USE_LAST_EPOCH: False                     # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 20
    DATASET: COHFACE
    DO_PREPROCESS: False                    # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/scratch/manne.sa/data/ACL_23/COHFACE/cohface/"          # Raw dataset path, need to be updated
    #CACHED_PATH: "/scratch/manne.sa/data/ACL_23/COHFACE/proc"    # Processed dataset save path, need to be updated
    CACHED_PATH: "/scratch/manne.sa/data/ACL_23/COHFACE/class_proc"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.7
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Standardized']
      #LABEL_TYPE: DiffNormalized # For regression
      LABEL_TYPE: Standardized  # For classification
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 72
      W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: EfficientPhys
  #MODE: regression
  MODE: classification
  #MODEL_DIR: 1221_cohface_effphys_regression
  MODEL_DIR: 0622_cohface_effphys_classification
  EFFICIENTPHYS:
    FRAME_DEPTH: 10
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  #MODEL_PATH:   "/scratch/manne.sa/workspace/checkpoints/rrr/checkpoints/2006_cohface_effphys/COHFACE_COHFACE_COHFACE_efficientphys_Epoch7.pth"
  #MODEL_PATH:   "/scratch/manne.sa/workspace/checkpoints/rrr/checkpoints/1221_cohface_effphys_regression/COHFACE_COHFACE_COHFACE_efficientphys_Epoch2.pth"
  #MODEL_PATH:   "/scratch/manne.sa/workspace/checkpoints/rrr/checkpoints/1221_cohface_effphys_classification/COHFACE_COHFACE_COHFACE_efficientphys_Epoch2.pth"
  MODEL_PATH:   "/scratch/manne.sa/workspace/checkpoints/rrr/checkpoints/0622_cohface_effphys_classification/COHFACE_COHFACE_COHFACE_efficientphys_Epoch7.pth"
